LCSubstring_CPP_RUN: LCSubstring_CPP
	./LCSubstring_cpp < file.in

LCSubstring_CPP: LCSubstring.cpp
	g++ LCSubstring.cpp -o LCSubstring_cpp

LCSubstring_C_RUN: LCSubstring_C
	./LCSubstring_c < file.in

LCSubstring_C: LCSubstring.c
	gcc LCSubstring.c -o LCSubstring_c
	